### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by Kamilius** [SamKirkland/FTP-Deploy-Action#1]
Hi @SamKirkland,
for some reason action's not appearing in "Visual Editor" at all, after pasting it through "Edit File" step. Did it happen to you before?

**Comment by SamKirkland** [comment]
Could you be missing the "resolves" key on the previous workflow step? "resolves" needs to be the same name as the action, in the example it's "FTP-Deploy-Action"

Here is an example of the entire workflow code:

```
workflow "Publish Website" {
  on = "push"
  resolves = ["FTP-Deploy-Action"]
}

action "FTP-Deploy-Action" {
  uses = "SamKirkland/FTP-Deploy-Action@master"
  secrets = ["FTP_USERNAME", "FTP_PASSWORD", "FTP_SERVER"]
}
```

**Comment by SamKirkland** [comment]
@Kamilius Did that resolve the issue?

**Comment by SamKirkland** [comment]
It's been a week without a response, I'm assuming this resolved your issue.
Let me know if it didn't.

**Comment by Kamilius** [comment]
@SamKirkland yeah, I was missing resolve and overall understanding of GitHub actions workflows.

Thanks for help, and sorry for not answering, I've spotted those answers only today's morning.
