### ISSUE TITLE
Is the .git folder necessary on the FTP server? 

### ISSUE THREAD

**Issue by jcolls** [SamKirkland/FTP-Deploy-Action#10]
I'm wondering if the .github and .git folders are required to be uploaded to the FTP server?
For example are they used at all to monitor which files to update or delete on the server end.   

If they are not used would you be able to provide an example of how to exclude multiple filers/folders using  --exclude-glob=GP  please.

**Comment by SamKirkland** [comment]
.git* files/folders are not needed by the action. The action doesn't look at any source files during deployment.

You can use `--exclude-glob=**/.git*/** --exclude-glob=**/.git**`
You will have to manually delete the .git/.gitignore/etc files/folder on the server yourself or add `--delete-excluded`

Full example:
```shell
on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@master
      env:
        FTP_SERVER: ftp.teachers-salaries.com
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        ARGS: --delete --exclude=.ftpquota --exclude-glob=**/.git*/** --exclude-glob=**/.git**
```

**Comment by jcolls** [comment]
Brilliant.  Thank you and thank you for the example.

**Comment by saltnpixels** [comment]
hello. This did not seem to work for me.
The .git and .github folders still get uploaded via ftp even after i deleted them and ran a push again.

**Comment by SamKirkland** [comment]
@saltnpixels sorry about that this answer is actually out of date (I've gone ahead and corrected the answer above).

You actually want `--exclude-glob=.git*/** --exclude-glob=.git**` ([see FAQ](https://github.com/SamKirkland/FTP-Deploy-Action#faq))
