### ISSUE TITLE
React deployment doesn't work unless I commit build folder

### ISSUE THREAD

**Issue by margaiwangara** [SamKirkland/FTP-Deploy-Action#101]
Hello,
Firstly, I would like to thank you for this package, it has really helped me perform continuous deployment with smoothly to my FTP server without much hassle, I honestly appreciate it. 
Based on your documentation, I can upload my react build folder to my server without commiting it by adding `!build` to my .git-ftp-include file, however, I have tried but it tells me that the build folder cannot be found, when I remove `build` folder from .gitignore and commit then push to github it uploads to my FTP server. How can I solve this problem because I am trying to avoid pushing my build folder to github.

**Comment by LukasFritzeDev** [comment]
Have you tried adding `!build/` to your `.git-ftp-include` file? Note the `/`.

**Comment by margaiwangara** [comment]
@LukasFritzeDev thank you for your reply. I have tried adding the / but still the same issue. I can't seem to be able to commit my react build folder without pushing it to Github. Maybe there is something that I missed, whenever you have time I would really appreciate it if you check out the repository I am talking about.
[Code Repository](https://github.com/margaiwangara/accumulate-client)

**Comment by SamKirkland** [comment]
Looking at your action logs you are getting the following error `fatal: 'build' is not a directory! Exiting...`

It appears you are doing the following:

1. Checking out the latest code
2. Building the code, then caching - good idea, I've been meaning to explore `actions/cache`
3. 🔥🔥 You then **get the latest code again** -  I'm pretty sure this removes the build folder 🔥🔥 
4. Run the publish script, which errors out because the build folder no longer exists


Can you try **removing** the following from your "Deploy to ftp server" step
```yml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
```

**Comment by SamKirkland** [comment]
Any updates on this? Did the change work?

**Comment by margaiwangara** [comment]
Hello, sorry I wasn't able to give early feedback based on the suggestion you presented. I tried what you suggested and unfortunately, the problem still persists.

**Comment by margaiwangara** [comment]
Finally managed to make it work, removed the deploy job and placed all the steps under one job, your initial suggestion of placing `!build/` folder in .git-ftp-include file is the solution. I'll add my code below incase someone faces the same problem.

`yml
name: Client-Side Code For Accumulate App With React.js
'on':
  push:
    branches: master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build React Project
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache/Restore node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: false

      - name: List output files
        run: find build/ -print

      - name: Deploy to ftp server
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: '${{ secrets.FTP_SERVER }}/accumulate/'
          ftp-username: '${{ secrets.FTP_USERNAME }}'
          ftp-password: '${{ secrets.FTP_PASSWORD }}'
          local-dir: build
`
