### ISSUE TITLE
Delete specific files on the FTP host

### ISSUE THREAD

**Issue by andersbea** [SamKirkland/FTP-Deploy-Action#107]
Is there any way to configure the FTP Deploy Action to delete specific files or not delete files. I am deploying an angular application and want to keep an assets folder which is located in the same destination folder.

- DistinationFolder
  - AssetsFolder          } The deploy action should ignore this folder
  - index.html             } But delete all the other files within the folder
  - ....

If not possible with FTP-Deploy-Action, is there another way to perform this task?

**Comment by SamKirkland** [comment]
This can be done in version 4 using the `exclude` argument.
