### ISSUE TITLE
Question: Clear directory / remove old files

### ISSUE THREAD

**Issue by Dominic-Marcelino** [SamKirkland/FTP-Deploy-Action#109]
Hey, first of all thanks for this awesome action. It saves me a lot of time! I've one open question:

**Usage**
I'm using a two-step action that
1. creates a new build and
2. uses this action to upload the build. 

Therewith the whole build is not tracked in git. Is there any option to remove old files from the server, that do not exist anymore in the new build? 

As far I could find out, there has been delete argument in the past... Will v4 be able to manage this via the described directory listing, or does this only applies to tracked files? 

Thanks and best regards,
Dominic

**Comment by SamKirkland** [comment]
You are correct, Version 4 resolves this, and it's out now!
