### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by PlugFox** [SamKirkland/FTP-Deploy-Action#127]
Error with self signed certificate

```
----------------------------------------------------------------
---------------  🔥🔥🔥 A error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  Full Error below  ----------------------
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
Error: Error: self signed certificate
```

**Comment by PlugFox** [comment]
Maybe add a flag allowing self signed certificate

**Comment by Wohlstand** [comment]
I got the same too... The hosting provider that I use, provides the FTPS access, and gives the self-signed certificate just for work. I can't affect it.

**Comment by timgaunt** [comment]
Same here, we've set `security: loose` expecting that to resolve it but it doesn't help. All our servers are self-signed and it's not something we can change frustratingly

**Comment by colmtroy** [comment]
has anyone found a workaround for this?
I get this issue when attempting to connect to a machine where the hostname is an IP (so no FQDN for the host).
Surely there should be some way to allow the connection handshake to complete?

**Comment by wcramos** [comment]
Hi ! Having same issue. security: loose seems to not change anything. Any other suggested work-around ?

**Comment by timgaunt** [comment]
We swapped over to FTP in the meantime which works but not ideal

**Comment by javafrog** [comment]
Hi, I'm having the same issue. Using unencrypted FTP is no solution for me =/

**Comment by mxmxcz** [comment]
This is probably related to the following pull request: https://github.com/SamKirkland/ftp-deploy/pull/5

The fastest workaround is to use, paradoxically, `security: strict` (I just successfully tested it). Be sure to specify the action version so this doesn't break your pipeline again when/if this gets fixed.

**Comment by javafrog** [comment]
> 
> 
> This is probably related to the following pull request: [SamKirkland/ftp-deploy#5](https://github.com/SamKirkland/ftp-deploy/pull/5)
> 
> The fastest workaround is to use, paradoxically, `security: strict` (I just successfully tested it). Be sure to specify the action version so it doesn't break your pipeline again when/if this gets fixed.

That indeed did the trick. Funny =)
