### ISSUE TITLE
Question: about state-name

### ISSUE THREAD

**Issue by bryx** [SamKirkland/FTP-Deploy-Action#128]
Hello,

I'm looking for more information about: state-name. I would like to know if it is mandatory to fill in the folder even if the server-dir was filled in before the field ? If I add the dev/ he tells me he can't find the file.

Example :
- name: 📂 Sync files
  uses: SamKirkland/FTP-Deploy-Action@4.0.0
  with:
    server: ftp.cluster023.hosting.ovh.net
    username: ${{ secrets.SYMFONY_FTP_USERNAME }}
    password: ${{ secrets.SYMFONY_FTP_PASSWORD }}
    server-dir: dev/
    state-name: .sync-state.json
    exclude: .git* 
      - .git*/** 
      - .vscode/**
      - .github/**

Example 2 :
- name: 📂 Sync files
  uses: SamKirkland/FTP-Deploy-Action@4.0.0
  with:
    server: ftp.cluster023.hosting.ovh.net
    username: ${{ secrets.SYMFONY_FTP_USERNAME }}
    password: ${{ secrets.SYMFONY_FTP_PASSWORD }}
    server-dir: dev/
    state-name: dev/.sync-state.json
    exclude: .git* 
      - .git*/** 
      - .vscode/**
      - .github/**

Merci,
Bryan

**Comment by SamKirkland** [comment]
Hello,

Good question. The  servers state file (`state-name`) is always uploaded to the `server-dir` folder. The `server-state` option exists for users who need to customize the name of the state (not the location).

So use example 1
