### ISSUE TITLE
Vulnerability issue when deploying website

### ISSUE THREAD

**Issue by adripo** [SamKirkland/FTP-Deploy-Action#135]
**Bug Description**
If I use this plugin to deploy a website, the `.ftp-deploy-sync-state.json` file will be created on the public part of the website and it contains the detail of all files available on that website.
A solution can be to create that file outsite the www folder.

**My Action Config**
```name: 🚀 Deploy website on push
on: push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: www/
          exclude: '[.git*, .git*/****]'
          dry-run: false
```

**Comment by adripo** [comment]
I tried to use absolute path for the state-name file and it seems to work, but I still get a wrong log in the output

`Sync complete. Saving current server state to "www//.ftp-deploy-sync-state.json"`

This is the cose I added:
`state-name: /.ftp-deploy-sync-state.json`

**Comment by AlexMayol** [comment]
If you have access to you server config, or to an `.htaccess` file or similar, you can deny the access to that .json file in particular.

**Comment by SamKirkland** [comment]
Yep as @AlexMayol said using `htaccess` (or similar, depending on your server) is the intended use-case.

I can look into adding official support & documenting this. You could probably get away with a relative path like this `../.ftp-deploy-sync-state.json` if you want to logs to be more clear.

**Comment by adripo** [comment]
Of course using `htaccess` is an option, but I prefer the relative path solution.
As I said in my last comment, by using the relative path, everything works right, exceptthe fact that the log that came out is wrong

Sync complete. Saving current server state to "**www//.ftp**-deploy-sync-state.json"

**Comment by DanielRuf** [comment]
It's a bit irritating but I have two `.ftp-deploy-sync-state.json` files. One in the root folder of the FTP and one in the public folder. But the one at the root level is newer. Can we delete the one in the public folder? It contains almost the same content.

**Comment by DanielRuf** [comment]
I think this is a bug because the file in the public folder is never updated (it seems so) and there should be probably only one file.

**Comment by AlexMayol** [comment]
> It's a bit irritating but I have two `.ftp-deploy-sync-state.json` files. One in the root folder of the FTP and one in the public folder. But the one at the root level is newer. Can we delete the one in the public folder? It contains almost the same content.

Yeah, there should be only one `.ftp-deploy-sync-state.json` file, at root level. The other one does nothing.
