### ISSUE TITLE
SFTP Deploy Action

### ISSUE THREAD

**Issue by sebastienserre** [SamKirkland/FTP-Deploy-Action#139]
I understood we can connect to server through FTP and FTPS, is it possible to connect through SFTP ?

Do you have any example of YAML instructions?

Thank you

**Comment by AlexMayol** [comment]
SFTP support was removed in V4, [as stated here.](https://github.com/SamKirkland/FTP-Deploy-Action/issues/102)

**Comment by SamKirkland** [comment]
Thanks @AlexMayol 

I plan on creating a separate action for SFTP eventually. SFTP is a entirely different protocol based on SSH that has a unfortunately similar name.
