### ISSUE TITLE
Is SFTP supported?

### ISSUE THREAD

**Issue by SGTGunner** [SamKirkland/FTP-Deploy-Action#14]
Greetings,

Is SFTP supported for this github action?

Thanks,

SGTGunner

**Comment by pelleknaap** [comment]
There is a beta branch for it (that should be merged soon), see #15 for more information

**Comment by SamKirkland** [comment]
SFTP support is live!
You can see an example usage in the readme

Make sure you're targeting v2.0.0 or master.
