### ISSUE TITLE
Action doesn't fail even if the process fails

### ISSUE THREAD

**Issue by Yanisky** [SamKirkland/FTP-Deploy-Action#150]
**Bug Description**
This might be 2 bugs but they happened in one build. I have this problem where the ftp operation is failing with a 533 error:

**My Action Log**
![image](https://user-images.githubusercontent.com/10558597/103174569-30083480-485b-11eb-9047-40c0012b9db2.png)

The reason it fails is because it never creates the .github folder, maybe because the task is assuming that anything that starts with a `.`  is a file?

And from the image below you can see that the folder `.github` is not being created

![image](https://user-images.githubusercontent.com/10558597/103174694-30ed9600-485c-11eb-8571-9027b39d02a6.png)

My biggest issue with it is that even with that error the action didn't fail as seen in the first image. I think the expected behviour would be for the action to fail and stop workflow execution.

**Comment by ThomasLeschley** [comment]
I have the same issue except with a different error (FTPError: 550 The process cannot access the file because it is being used by another process.).
Despite the error, the operation is considered successful which results in a false positive for my entire workflow.
Please fix this.

**Comment by SamKirkland** [comment]
version 4.1.0 should resolve this. Exceptions now bubble up and show cause the action to error out.
