### ISSUE TITLE
Success action, but no files on FTP

### ISSUE THREAD

**Issue by vallter2** [SamKirkland/FTP-Deploy-Action#154]
I have problem with uploading files on FTP,  after commit, action run... FTP connections is ok, option to "dangerous-clean-slate" is ok (delete all files in folder), but problem is with uploading new files. Log file is clear, action done. But no files on server.

**Comment by vallter2** [comment]
Done... I forgot to Fetch code

```
- name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
```
before
    
  ```
  - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
```

**Comment by bowieinflux** [comment]
Lol I had this issue as well, thanks for posting your fix.
