### ISSUE TITLE
IP restricted servers

### ISSUE THREAD

**Issue by CHEWX** [SamKirkland/FTP-Deploy-Action#155]
Hi,

Couldn't see anything in the docs about working with IP restricted servers? 

Thanks

**Comment by SamKirkland** [comment]
Can you expand on this a bit?

Do you have external access to your server blocked and you want to whitelist specific IP addresses? If that's the case you can look at [this document](https://docs.github.com/en/enterprise-server@2.22/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses)
