### ISSUE TITLE
Can we rename or delete a single file?

### ISSUE THREAD

**Issue by MrYossu** [SamKirkland/FTP-Deploy-Action#161]
I'm using this action to push my files to a server, but would like to be able to rename or delete a single file as part of the process.

Is this possible? Thanks

**Comment by MrYossu** [comment]
Turned out to be easy if you use python...

```
    - name: Rename app_offline.htm back to _app_offline.htm to start the site
      shell: python
      run: |
        import ftplib
        ftp = ftplib.FTP('${{ secrets.FTPSERVER }}')
        ftp.login('${{ secrets.FTPUSER }}', '${{ secrets.FTPPASSWORD }}')
        ftp.rename('jim.txt', 'jimmy.txt')
        ftp.quit()
```

Deleting is as simple as calling `ftp.delete('jim.txt')`.

Hope this helps someone.

**Comment by SamKirkland** [comment]
Thanks Avrohom,

Closing this out.
