### ISSUE TITLE
Add --no-progress

### ISSUE THREAD

**Issue by szepeviktor** [SamKirkland/FTP-Deploy-Action#164]
**Bug Description**
Hello! Please consider adding an option to disable progress indicator.
Thank you.

**My Action Log**
https://github.com/WordPress/theme-experiments/runs/1807684307?check_suite_focus=true

**Comment by SamKirkland** [comment]
Hello @szepeviktor version 4 has a `log-level` option that can be set to `minimal` to accomplish this. It will still log what files are being changed, but doesn't log as much as previous versions.

**Comment by szepeviktor** [comment]
Thank you.
