### ISSUE TITLE
NEW FEATURE: Allow setting exclude option in a external file

### ISSUE THREAD

**Issue by xannasavin** [SamKirkland/FTP-Deploy-Action#168]
So I recently updated to the latest action and I really love how simple everything goes! This is truely helpful.

However, Adding all the FTP ignore rules directly into the action get's quite messy and the overview is poor, since the editor here on github does not allow for comments between the rules (it shows an error).

Thus it would be great if the .git-ftp-ignore would be supported again, so the rules can be set in a cleaner overview.

**Comment by kevinblackdesk** [comment]
Relevant: https://github.com/SamKirkland/FTP-Deploy-Action/issues/156

**Comment by SamKirkland** [comment]
@xannasavin can you describe what kind of ignore rules you have? I'd love to make it cleaner and a real world use case would help.

**Comment by xannasavin** [comment]
Hi @SamKirkland you can see my exclude list here for instance:
https://github.com/SamKirkland/FTP-Deploy-Action/issues/169

What I like with the git-ftp-ignore is that I am able to input comments to make it more obvious for me what files I am referring to. The current approach seems not even to allow for a blank line between the exclusions without getting stuck (at least I believe that's one of the reasons for one or another problem, if I insert a blank line).

Since I'm working mainly on WordPress projects, each project has a few standard exclusions like all the git stuff, IDE related stuff etc. 
Additionally each project has some individual exclusions like draft folders, source file folders etc. that should not be synced to the server.

Another pro from my point of view for the git-ftp-ignore is that it's more easy to set it up, since the IDE helps creating the correct paths, whereas in the .yml file of the workflow this is not possible thus errors are more easy to make.
