### ISSUE TITLE
I would like to add an argument like --delete

### ISSUE THREAD

**Issue by PhilipMay** [SamKirkland/FTP-Deploy-Action#170]
Hi,
in one of the first versions it was possible to pass an argument like `--delete`.
That option was removed in this new version. Could you enable it again?
Thanks
Philip

**Comment by SamKirkland** [comment]
The new version enables deleting by default. What's your use-case for re-adding the delete option?

**Comment by PhilipMay** [comment]
> The new version enables deleting by default. 
I think I had files in the target folder that were not in the source folder and did not get deleted. Are you sure about that?

I will double check...

> What's your use-case for re-adding the delete option?

I generate a blog on GitHub and want to sync it to my hosting provider. I want that if a file gets deleted on source side that it also gets deleted on my hosting provider.

**Comment by SamKirkland** [comment]
If that's the case it's a bug or the files were excluded from the sync.

On each deployment the script checks the last deployment vs the current deployment and creates/deletes files as-needed.
If the files weren't in source control at the time of the last deployment the script doesn't know about them and can't delete them. For examples some users have uploaded files directly, and then want those files to be remove automatically, the script doesn't know about these direct changes so it won't delete the files.

If you want a full "clean slate" you can run the script once with `dangerous-clean-slate` and it will do a full purge and re-sync (this is the exact same as deleting all the files/folders and then running a deployment). Remove this after the initial deployment.

**Comment by PhilipMay** [comment]
> If you want a full "clean slate" you can run the script once with `dangerous-clean-slate` and it will do a full purge and re-sync (this is the exact same as deleting all the files/folders and then running a deployment). Remove this after the initial deployment.

Well, isn't delete all at target and then upload everything again very different from uploading only what is new and delete what is not available at source?

**Comment by SamKirkland** [comment]
Yes. The script will run a diff-only deploy by default. I'll rephrase what I believe to be the problem.

This action "syncs" content from source control to a FTP server. If any modification have been made outside of the action things will become out-of-sync. Is it possible that occurred here? If you would like to force a fresh sync you can use the `dangerous-clean-slate` option or manually delete all files and trigger the action again.

**Comment by PhilipMay** [comment]
Ok - thanks for the answer.
Could you please explain what dangerous-clean-slate exactly does? What is dangerous on this command?

**Comment by ilonashairstyling** [comment]
> 
> 
> Yes. The script will run a diff-only deploy by default. I'll rephrase what I believe to be the problem.
> 
> This action "syncs" content from source control to a FTP server. If any modification have been made outside of the action things will become out-of-sync. Is it possible that occurred here? If you would like to force a fresh sync you can use the `dangerous-clean-slate` option or manually delete all files and trigger the action again.

I understood before you could also delete '.ftp-deploy-sync-state.json' on the FTP destination folder, which would initiate a full deploy always @ next push?

**Comment by SamKirkland** [comment]
> Could you please explain what dangerous-clean-slate exactly does? What is dangerous on this command?

`dangerous-clean-slate` runs the `clearWorkingDir` command which "Removes all files and directories in the working directory without removing the working directory itself.". This command is used to purge the entire deployment folder. It's the same as logging into your ftp server and deleting the folder before running this action.

> I understood before you could also delete '.ftp-deploy-sync-state.json' on the FTP destination folder, which would initiate a full deploy always @ next push?

Correct. Deleting `.ftp-deploy-sync-state.json` and running the script will cause a fresh deploy
