### ISSUE TITLE
revision number

### ISSUE THREAD

**Issue by simon-ourmachinery** [SamKirkland/FTP-Deploy-Action#174]
It would be fantastic if you could say:
```
enable-revision: true
```
and then files with the same name will get a revision number when uploaded

**Comment by SamKirkland** [comment]
Can you expand on your use-case a bit more? We can re-open the issue if needed.
I'm not sure if I agree with the need for this because it goes against the concept of source control.

If you are looking to deploy a folder for every version you can look at my comment on issue #177
