### ISSUE TITLE
.git-ftp

### ISSUE THREAD

**Issue by Olzie-12** [SamKirkland/FTP-Deploy-Action#175]
how do i not push the .git-ftp.log? Its really annoying and i am running on 3.1.1 as my server that i use only supports SFTP

**Comment by SamKirkland** [comment]
Hello!

You can ignore specific files by creating a `.git-ftp-ignore` file. [A few examples exist in the docs](https://github.com/SamKirkland/FTP-Deploy-Action/tree/3.1.1#ignore-specific-files-when-deploying)
