### ISSUE TITLE
Suggestion: Store host and user name as secret

### ISSUE THREAD

**Issue by flschr** [SamKirkland/FTP-Deploy-Action#180]
I really love this  script and hope that you can implement the suggestion to save the hostname and username also as secret (not only the password). I would prefer to keep those informations private.

Thanks in advance
René

**Comment by NegativeStuff** [comment]
You can do this yourself by editing the yaml and then adding the secrets.

server: ${{ secrets.ftp_host }}
port: ${{ secrets.ftp_port }}
username: ${{ secrets.ftp_user }}
password: ${{ secrets.ftp_password }}

**Comment by flschr** [comment]
Oh wow! You are right. I didn't know that. Thanks a lot :)
