### ISSUE TITLE
Connection closed without reason

### ISSUE THREAD

**Issue by vdkuipb** [SamKirkland/FTP-Deploy-Action#19]
Hey,

I wanted to use this action but i encountered a problem. For information: i am using sftp, i know the username and password are correct and i am unsure of the port and host. Sometimes the run fails at the connection part and sometimes it doesn't (see images). I ran this action on my local computer and it works 100% of the time i run it. I hoped maybe someone encountered the same issue and someone knows how to fix this.

Thanks,

Bram

Failed run
![Screenshot 2019-11-07 at 16 08 44](https://user-images.githubusercontent.com/14052371/68401645-66c44c80-017a-11ea-98ca-c78102cce8cc.png)

Same run that i rechecked
![Screenshot 2019-11-07 at 16 14 10](https://user-images.githubusercontent.com/14052371/68401648-66c44c80-017a-11ea-8fec-c18554892159.png)

**Comment by SamKirkland** [comment]
Unfortunately I haven't seen this problem before.

Does it seem completely random? When it works have you published recently, or has it been an long time between publishes? Any sort of pattern you can find might help us narrow down the issue.

**Comment by vdkuipb** [comment]
Throughout the day I'll do some runs and post my findings here.

**Comment by vdkuipb** [comment]
Ok so i ran a simple test by incrementing a number in a html file and letting the workflow run on push. There doesn't seem to be any pattern to it. First it looked like it happened in turn but the second last run disproves that. The runs are in random interval from 5 mins to 1 hour.

![Screenshot 2019-11-08 at 11 28 18](https://user-images.githubusercontent.com/14052371/68469904-57e1a680-021b-11ea-81cf-a9016400e246.png)

**Comment by vdkuipb** [comment]
If there is anything that i can do to help, please let me know!

**Comment by SamKirkland** [comment]
I spent a few hours looking into this, I've had no luck narrowing down the issue.
Can you switch over to FTP and see if that resolves the issue?

**Comment by JordyValentine** [comment]
@vdkuipb Is it possible your host is blocking the connection? Mine sometimes does when I use many FTP sessions in a short period behind my VPN

**Comment by vdkuipb** [comment]
Thanks for the suggestions. Just an update from me: I use an external host that doesn't allow an ftp connection because it is 'old' and 'unsafe' so that option couldn't work for me. I'll contact my host again to check if they block Github for some reason. Thanks!

**Comment by JordyValentine** [comment]
Hopefully that leads somewhere. As I said occasionally my host blocks my home ftp connection and if I graphed it out it would be in a similar pattern to what you're seeing in your screenshot.

**Comment by vdkuipb** [comment]
Update: my hosting provider made some suggestions by looking at the logs. The first suggestion was that I was trying to mkdir the www folder by uploading straight to the www folder. I added a subfolder and started on uploading to that subfolder which in the end still didn't fix it as a whole. The second suggestion was that at the part where it tries to create a new certificate for the connection that the docker container accepts it too late, which as a result returns an error from my hosting provider. This could be a link to the MR made by @thijsniks https://github.com/SamKirkland/FTP-Deploy-Action/pull/21. If I get more information ill update again!

**Comment by vdkuipb** [comment]
I checked @thijsniks his website hosting provider and it seems we use the same hosting provider!

**Comment by SamKirkland** [comment]
> I checked @thijsniks his website hosting provider and it seems we use the same hosting provider!

Haha that's a huge coincidence!

My host (a2hosting) requires the initial sshpass step otherwise the script will get stuck on the "Uploading files..." step.
I've been working on a newer version of this action that will hopefully fix some of these issues, the new version will attempt to add the ssh key but will continue if that step fails. I'm not sure if this will fix your issue, i saw your comment over on the pending PR.
I've been having a lot of issues that are host dependent so i can't test them, maybe it's time I buy a few basic hosting plans so i can add providers to my automated tests. Do you mind telling me your current hosting provider?

**Comment by vdkuipb** [comment]
I currently host at https://www.transip.nl, but if I can do anything to test the newer version please tell me, because I would be happy to help!

**Comment by JordyValentine** [comment]
I don't have any problems with the action using Hawk Host [hawkhost.com](hawkhost.com) so you can rule them out for now

**Comment by SamKirkland** [comment]
@JordyValentine and @vdkuipb I recently changed the underlying library to [git-ftp](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md) which vastly improves how connections are established.

Can you migrate to v3 and see if it's resolved this issue?

-----

Keep in mind v3 will only sync tracked (comitted) files by default. So if your file isn't in github it won't be uploaded. To change this use a custom `.git-ftp-include` file.

**Comment by SamKirkland** [comment]
version 4 resolves this. Please upgrade to the latest version.
