### ISSUE TITLE
Exclude Function not working

### ISSUE THREAD

**Issue by coloralp** [SamKirkland/FTP-Deploy-Action#203]
Hi the exclusion given as an example is not working. It gives syntax error on github.

**Comment by baba43** [comment]
Same here.

**Comment by superhize** [comment]
Hey, you can use
`exclude: '.git*, .git*/**, README.MD]'`
https://github.com/SamKirkland/FTP-Deploy-Action/issues/202#issuecomment-869806105
#200

**Comment by DemianX0** [comment]
Duplicate of #202

**Comment by christrunk** [comment]
Agreed here, the documentation is wrong, it's missing the single quote wrapper

**Comment by SamKirkland** [comment]
Duplicate of #202
