### ISSUE TITLE
Fetch from remote server to github repo ?

### ISSUE THREAD

**Issue by Yyatiko** [SamKirkland/FTP-Deploy-Action#210]
Hi,

Thanks for this action. It works fine for me.

Is it possible to do the reverse operation, i.e. reversing direction of transfer ? I would like that all the files from my remote server be fetch to my git hub repo. This could be triggered manually via github website or a specific URL link.

This would be nice because my website is modified on the remote server and I would like to update my repo when this happend.

Thanks

**Comment by SamKirkland** [comment]
This would be possible by running some commands to download code and then commit it to your GitHub project. However this seems like a very specific use case and I want this action to support the general use case.

If you wanted to perform the above operation you could run those download/commit commands within your yaml file.

**Comment by AudioSutta** [comment]
@ SamKirkland

Thank you very much for your answer. I will see how I can do that in the yaml file as you say.
