### ISSUE TITLE
Server doesnt exist

### ISSUE THREAD

**Issue by SignatureDom** [SamKirkland/FTP-Deploy-Action#212]
![image](https://user-images.githubusercontent.com/71554049/127893565-ae79f982-4563-4715-8a43-68915f553695.png)
![image](https://user-images.githubusercontent.com/71554049/127893596-45b4ce1a-b681-4b22-b77b-c54aed558584.png)

**Comment by HikwaMehluli** [comment]
Look at this documentation https://github.com/marketplace/actions/ftp-deploy#ftps

On how to write out ftps server deploy
