### ISSUE TITLE
Docker build failed with exit code 100

### ISSUE THREAD

**Issue by abdulawal39** [SamKirkland/FTP-Deploy-Action#216]
**Bug Description**
I am using version 3.0.0 & it's been working just fine. But today, I started getting error on every run. Its not working anymore. I also tried changing to version 3.1.1, the same thing is happening. Any idea how it can be solved?

**My Action Log**
```
E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

**Comment by andyUSDigital** [comment]
I have this problem too. I've also tried changing the runs-on to `ubuntu-18.04` and `ubuntu-latest` with no luck.

Hoping there's a solution soon!

**Comment by seatgeek-cws** [comment]
We are also getting this issue, using version 3 for sftp. Thanks

**Comment by SamKirkland** [comment]
Looks like `debian` published a new version "Debian 11 - bullseye" over the weekend. That's the likely cause.

Looking into this.

**Comment by otaviofavero** [comment]
I'm also going through the same problem

im changing the runs-on to ubuntu-18.04 and ubuntu-latest with no luck

it seems that there was a change in the repository
http://security.debian.org/debian-security/

**Comment by BWS-Andreas** [comment]
Ah, I am not alone with this problem!
Where exactly in debian can I find what to do?

**Comment by Olzie-12** [comment]
> Looks like `debian` published a new version "Debian 11 - bullseye" over the weekend. That's the likely cause.
> 
> Looking into this.

do you know any ETA of this fix?

**Comment by SamKirkland** [comment]
This issue should now be resolved. I've updated versions `3.0.0`, `3.1.0`, and `3.1.1` with a fix. Note, if the action has not run for several commits you will be behind your latest code. This means you will need to increase the `fetch-depth` option so the action sees all the missed commits.

If you see a "Uploading all files since no commit was found" message, that's due to your commits being behind. This issue will also resolve itself, but requires a full deploy which can take a while.

```yaml
name: Publish Website
jobs:
  FTP-Deploy:
    name: Publish Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 100
```

---

Please update to the version 4.1.0 if you can. Thanks.

**Comment by Olzie-12** [comment]
> This issue should now be resolved. I've updated versions `3.0.0`, `3.1.0`, and `3.1.1` with a fix. Note, if the action has not run for several commits you will be behind your latest code. This means you will need to increase the `fetch-depth` option so the action sees all the missed commits.
> 
> If you see a "Uploading all files since no commit was found" message, that's due to your commits being behind. This issue will also resolve itself, but requires a full deploy which can take a while.
> 
> ```yaml
> name: Publish Website
> jobs:
>   FTP-Deploy:
>     name: Publish Website
>     runs-on: ubuntu-latest
>     steps:
>       - uses: actions/checkout@master
>         with:
>           fetch-depth: 100
> ```
> 
> Please update to the version `4.1.0` if you can. Thanks.

We would update to 4.1.0 but no SFTP support, but thanks for the fix

**Comment by andyUSDigital** [comment]
Thanks for the fix Sam!
