### ISSUE TITLE
SSH Private Key

### ISSUE THREAD

**Issue by sebastienserre** [SamKirkland/FTP-Deploy-Action#23]
Hello,
Is a way exists to specify a private key io a password ?

Many thanks for your job

**Comment by ShawnYcx** [comment]
I'm looking for a way to include a private key with the sftp connection, too. Is there a way to do this currently?

**Comment by SamKirkland** [comment]
> I'm looking for a way to include a private key with the sftp connection, too. Is there a way to do this currently?

Not currently. I'll be adding this feature with v3

**Comment by ShawnYcx** [comment]
Thanks!

**Comment by gto1** [comment]
This would be great, I think then we could use it to deploy to AWS Lightsail apps.

**Comment by SamKirkland** [comment]
Hey guys!

With the release of V3 I've change to a new underlying library [git-ftp](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md). This library supports `--key`, `--pubkey`. and `--cacert <file>`.
It looks like `--key` would solve this use case but I haven't been able to test it.

----

Note v3 has some breaking changes, notably only tracked (committed) files are published by default. If your file isn't in source control you will have to add it `.git-ftp-include` [see example](/SamKirkland/FTP-Deploy-Action#force-upload-specific-files)

**Comment by gto1** [comment]
I’ll def test it out. Sorry been too busy lately. Will try!
