### ISSUE TITLE
Login failed: 550 SSL/TLS required on the control channel

### ISSUE THREAD

**Issue by sebastienserre** [SamKirkland/FTP-Deploy-Action#25]
Hello,
When using sftp the action do not make error but no files are transferred :-(
I try by ftp and got the error "Login failed: 550 SSL/TLS required on the control channel" any idea on what's wrong ?

Many thanks for your job

**Comment by gto1** [comment]
Awesome Action, I am having a lot of fun with it. I am seeing the same error as above. I FTP with Filezilla to my host using FTP, Port 21, and the setting of "Use explicit FTP over TLS" and it connects just fine. But with this Action, on the `FTP-Deploy-Action` step I am getting:

>Using ftp to connect to port 21
Uploading files...
mirror: Login failed: 550 SSL/TLS required on the control channel
##[error]Docker run failed with exit code 1

**Comment by gto1** [comment]
Awesome Action, I am having a lot of fun with it. I am seeing the same error as above. I FTP with Filezilla to my host using FTP, Port 21, and the setting of "Use explicit FTP over TLS" and it connects just fine. But with this Action, on the `FTP-Deploy-Action` step I am getting:

>Using ftp to connect to port 21
Uploading files...
mirror: Login failed: 550 SSL/TLS required on the control channel
##[error]Docker run failed with exit code 1

**Comment by SamKirkland** [comment]
@gto1 what web host are you using?

**Comment by gto1** [comment]
Hey @SamKirkland I am trying to do this with a simple, shared PHP account at https://cfdynamics.com.

**Comment by SamKirkland** [comment]
@sebastienserre and @gto1  I recently changed the underlying library to [git-ftp](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md) which vastly improves how connections are established.

Can you [migrate to v3](/SamKirkland/FTP-Deploy-Action/releases) and see if it's resolved this issue?

-----

Keep in mind v3 will only sync tracked (comitted) files by default. So if your file isn't in github it won't be uploaded. To change this use a custom `.git-ftp-include` file.

**Comment by sebastienserre** [comment]
Hello,
In v3 I can connect but with the `--insecure` params for now... do not well understand how to use my SSh key

**Comment by SamKirkland** [comment]
Great news!

I plan on adding documentation on `--key` usage soon.
For now i'll close this issue.

**Comment by stefan-niedermann** [comment]
@sebastienserre i am facing the same issue. Could you tell me please how the `--insecure` flag can be used within the GitHub action? Do i have to append it in the yaml file (cause i have never seen passing parameters to actions this way before)?

**Comment by SamKirkland** [comment]
@stefan-niedermann [please this example in the docs](https://github.com/marketplace/actions/ftp-deploy?version=3.1.1#ftps-file-transfer-protocol-over-ssl)
