### ISSUE TITLE
(Suggestion) Key to include ".github" Directory

### ISSUE THREAD

**Issue by Minionguyjpro** [SamKirkland/FTP-Deploy-Action#252]
If you add an key to include the ".github" Would be handy for some developers, to use it as complete backup or something else.

**Comment by SamKirkland** [comment]
You can accomplish this by using the `exclude` setting. The current default for this setting excludes `.git*` files/folders and well as `node_modules` but it can be customized.

**Comment by Minionguyjpro** [comment]
But how?

**Comment by SamKirkland** [comment]
The readme has a few examples

'''yaml
exclude: |
  **/node_modules/**
'''
