### ISSUE TITLE
Issues with --exclude and --include

### ISSUE THREAD

**Issue by NathanBlennd** [SamKirkland/FTP-Deploy-Action#26]
I'm trying to use the --exclude and --include ARGS to exclude everything except a few files and everything in one certain directory. I'm not sure that's possible, but hopefully it is. I've been trying:

`--exclude '.*'
--exclude '.*/'
--include 'public_html/github-actions-test/.gitattributes'
--include 'public_html/github-actions-test/.gitignore'
--include 'public_html/github-actions-test/wp-content/themes/github-actions-test*'
--include 'public_html/github-actions-test/wp-content/themes/github-actions-test*/'
--exclude-glob=.git*/**
--exclude-glob=.git**
--dry-run`

The above doesn't work, and I'm just wondering if this is possible.

**Comment by SamKirkland** [comment]
It should be possible solely with include/exclude, however it's pretty hard to debug.

You could manually delete all the files you want to skip prior to running the deploy action using normal "rm" commands (none of your removals will be committed to your project)

See an example of this on issue #22

**Comment by SamKirkland** [comment]
Have you had any more time to look at this? Any luck?

**Comment by NathanBlennd** [comment]
I haven't had any luck getting this to work. I know it should be possible, but I can't figure out the correct includes and excludes to get it to work. In the meantime, I've found that using git ftp push allows me to do the same thing that I wasn't to with lftp, so I switched to that.
