### ISSUE TITLE
NEW FEATURE: Zip/Compress existing remote directory before the deployment

### ISSUE THREAD

**Issue by sunethshehan** [SamKirkland/FTP-Deploy-Action#261]
Hi,

Can we zip/compress the existing remote directory before the deployment, it would be better because we can replace it if anything went wrong in the new build 🙂

**Comment by SamKirkland** [comment]
Hello Suneth,

I like the idea. But if something goes wrong you should just deploy the old git commit :)
This is generally referred to as "rolling back"

If you want to accomplish something like this I recommend zipping the contents before each deployment and then uploading that file as a version.

Either way this is outside the scope of what this action is doing (sync git --> server)

**Comment by sunethshehan** [comment]
Hello Sam,

Yes!! Great idea! Thanks... 🙂👍
