### ISSUE TITLE
How to upload to root folder?

### ISSUE THREAD

**Issue by AleksandrovC** [SamKirkland/FTP-Deploy-Action#264]
Is there a non-hacky to just upload to the root folder?

**Comment by SamKirkland** [comment]
`server-dir` is optional. If you don't specify this option it will upload to whatever the default FTP server is for your client.

So by default this action will upload to the "root" folder (assuming by root you mean the default folder you see when logging into that FTP account).

Is this the answer you are looking for? There's not much context here, next time please post more context.

**Comment by AleksandrovC** [comment]
The action settings i use are:

`
on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.domain.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
`
`

**Comment by AleksandrovC** [comment]
> `server-dir` is optional. If you don't specify this option it will upload to whatever the default FTP server is for your client.
> 
> So by default this action will upload to the "root" folder (assuming by root you mean the default folder you see when logging into that FTP account).
> 
> Is this the answer you are looking for? There's not much context here, next time please post more context.

Thanks - this looks helpful 👍
I`m going to modify the path directly from the  FTP server client.
