### ISSUE TITLE
Failed on RM

### ISSUE THREAD

**Issue by sebastienserre** [SamKirkland/FTP-Deploy-Action#27]
Hello

I still have some trouble with the script
```Uploading files...
rm: Access failed: Failure (generated)```
is a way exists to know why it failed ?

**Comment by SamKirkland** [comment]
The FTP account you're using doesn't have access to delete that folder/file on the server.

You can resolve this by either:
1) update the FTP account permission to have delete access to those folders/files
2) remove the `--delete` argument
3) tell the deploy action to skip this file by using the exclude or exclude glob option

**Comment by SamKirkland** [comment]
Have you had any more time to look at this? Any luck?

**Comment by sebastienserre** [comment]
Thanks, I will check asap.

**Comment by sebastienserre** [comment]
It's OK, was my fault, many thx for your tool
