### ISSUE TITLE
node_modules won't be excluded

### ISSUE THREAD

**Issue by khaledrakhisi** [SamKirkland/FTP-Deploy-Action#277]
When I use the following :
exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**

not only folders won't be excluded but addition folders will be added too!?
So why is that

**Comment by SamKirkland** [comment]
Node modules is excluded by default. So you don't need to changing the defaults.

You need to be using file globs instead (`**`). See readme for more info. See the defaults for an example
