### ISSUE TITLE
Sync error when you delete a folder with subfolders

### ISSUE THREAD

**Issue by JaviRpo** [SamKirkland/FTP-Deploy-Action#279]
**Bug Description**
This is my folders structure
```
📁 www
     📁 app
         ➕ file1, file2, ..., fileN
     📁 assets
          📁 excel
              ➕ file1, file2, ..., fileN
          📁 pdf
              ➕ file1, file2, ..., fileN
         ➕ file1, file2, ..., fileN
```
If I remove the `assets` folder and all of its children elements (folders and files) the deploy process will be:
* List all folders and files to delete (Sorted by path name), [DiffResult.delete](https://github.com/SamKirkland/ftp-deploy/blob/f79bd104c89cbbf01c51e48cdd08efa522074e39/src/types.ts#L111) will have the next list:
```
📁 www/assets
➕ www/assets/file1
➕ www/assets/file2
➕ www/assets/...
➕ www/assets/fileN
📁 www/assets/excel
➕ www/assets/excel/file1
➕ www/assets/excel/file2
➕ www/assets/excel/...
➕ www/assets/excel/fileN
📁 www/assets/pdf
➕ www/assets/pdf/file1
➕ www/assets/pdf/file2
➕ www/assets/pdf/...
➕ www/assets/pdf/fileN
```
* Next the delete process will be:
   * [Delete files](https://github.com/SamKirkland/ftp-deploy/blob/f79bd104c89cbbf01c51e48cdd08efa522074e39/src/syncProvider.ts#L173-L176) first. No problem with this.
   * [Delete folders](https://github.com/SamKirkland/ftp-deploy/blob/f79bd104c89cbbf01c51e48cdd08efa522074e39/src/syncProvider.ts#L178-L181) next. And here is the problem, because the process will try to delete the parent folder `📁 www/assets` before delete the children folders `📁 www/assets/excel` and `📁 www/assets/pdf` and the process have

**My Action Config**
Any normal default config

**My Action Log**
```
removing "www/assets/file1"
removing "www/assets/file2"
removing "www/assets/fileN"
removing "www/assets/excel/file1"
removing "www/assets/excel/file2"
removing "www/assets/excel/fileN"
removing "www/assets/pdf/file1"
removing "www/assets/pdf/file2"
removing "www/assets/pdf/fileN"
removing folder "www/assets/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't change directory to assets/: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4744:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4585:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Can't change directory to Carbon/: No such file or directory
```

I guess the solution could be in the here in [HashDiff.getDiffs](https://github.com/SamKirkland/ftp-deploy/blob/f79bd104c89cbbf01c51e48cdd08efa522074e39/src/HashDiff.ts#L45-L46) sorting the files backwards, because you will have the list in this way:

```
➕ www/assets/pdf/fileN
➕ www/assets/pdf/...
➕ www/assets/pdf/file2
➕ www/assets/pdf/file1
📁 www/assets/pdf
➕ www/assets/excel/fileN
➕ www/assets/excel/...
➕ www/assets/excel/file2
➕ www/assets/excel/file1
📁 www/assets/excel
➕ www/assets/fileN
➕ www/assets/...
➕ www/assets/file2
➕ www/assets/file1
📁 www/assets
```
and the children folders delete will be first.

**Comment by klodianpepkolaj** [comment]
My team is having same issue

**Comment by timocouckuyt** [comment]
You should upgrade to 4.3.0. See closed issue #220.

**Comment by klodianpepkolaj** [comment]
> You should upgrade to 4.3.0. See closed issue #220.

We already have 4.3.0

**Comment by timocouckuyt** [comment]
@JaviRpo's post clearly stated 4.2.0. in the error message. @klodianpepkolaj your problem is clearly some other issue, perhaps start a new thread?

**Comment by JaviRpo** [comment]
@timocouckuyt thanks, it works with latest version
