### ISSUE TITLE
Delete TEMP folder when deploying

### ISSUE THREAD

**Issue by emololftw** [SamKirkland/FTP-Deploy-Action#281]
Hello guys,

is there an opinion how to remove/recreate folder in repository? I have temporary folder for database things and want delete whole content after ftp deploy.

Thank you!

**Comment by ifui** [comment]
I have a suggest. You create a shell file, after visit webhook and call it.

**Comment by SamKirkland** [comment]
Correct, I would like to keep this action as simple as possible. If you want to run something before/after a sync complete that will need to be custom.
