### ISSUE TITLE
How configure for deploy only changes and not all project?

### ISSUE THREAD

**Issue by merabchik** [SamKirkland/FTP-Deploy-Action#286]
How configure for deploy only changes and not all project?

**Comment by SamKirkland** [comment]
By default v4+ only deploys changes. If you are seeing all files deploy on every publish please submit a bug report

**Comment by merabchik** [comment]
I have this version "SamKirkland/FTP-Deploy-Action@4.3.0"
but when I push Angular project there going deployment of asset files what is not changed, that's why I mention this feature

**Comment by SamKirkland** [comment]
Hmm that's not good. If you post your log and configuration I can help debug
