### ISSUE TITLE
Could you release major version(s) of your GitHub action?

### ISSUE THREAD

**Issue by jmfayard** [SamKirkland/FTP-Deploy-Action#294]
Bonjour! 🇫🇷

I contribute to [GitHub Actions Kotlin DSL](https://github.com/krzema12/github-actions-kotlin-dsl) which provides an alternative to write GitHub Actions not in YAML but in a type-safe programming language: Kotlin.

To this end we provide type-safe wrappers for currently [72 (and counting) wrapper actions](https://krzema12.github.io/github-actions-kotlin-dsl/supported-actions/). Those type-safe wrappers are generated from its `action.yml` which we update when it goes to a new major version, for example `actions/cache@v2` to `actions/cache@v3`

And of course we support your action as well!

Unfortunately when an action don't have a major version, which is what GitHub recommands, we are forced to update manually for every minor version, like from `appleboy/scp-action/v0.1.2` to `appleboy/scp-action/v0.1.3` 

See [our issue here](https://github.com/krzema12/github-actions-kotlin-dsl/issues/289)

Would you consider creating a major version for your action?
That would make our life easier, and the life of your users easier in general.

You can find here the recommendations from GitHub:

[https://github.com/actions/toolkit/blob/main/docs/action-versioning.md](https://github.com/actions/toolkit/blob/main/docs/action-versioning.md) 
(see *Recommendations* in particular)

**Comment by jmfayard** [comment]
Note: in practice this  is done by pushing a tag `v1` to your latest `1.x.y` release

```bash
git tag -fa v1 -m "Update v1 tag"
git push origin v1 --force
```

**Comment by SamKirkland** [comment]
I already do this (see tags for versions)
