### ISSUE TITLE
Use line grouping for logs

### ISSUE THREAD

**Issue by itsvyle** [SamKirkland/FTP-Deploy-Action#300]
Hi,

This is not really an issue, but an enhancement. I think that you could use line grouping (see [documentation](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines) for output, especially in `log-level: standard` and `log-level: verbose` modes.

This would compact all the lines for the `Calculating differences between client & server` and the `Making changes` actions, making the logs way more readable.

Thank you for taking the time to read this,

**Comment by PauloMatosStepIn** [comment]
Hello,

How can I use my secrets on the execution of this Git Hub Action:

name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: (my ftp site address)
        username: (my ftp site user)
        password: ${{ secrets.ftp_password }}

I get the error:
        Error: Input required and not supplied: password

The secrets is created, but the secrets can not be used with forked packages,
what is the recomend solution/work around?
keep password clear is not an option for security reasons

thank you in advance

**Comment by SamKirkland** [comment]
Decided not to implement, I'm worried people will copy logs in issues without expanding them first 😢
