### ISSUE TITLE
Add support for SSH

### ISSUE THREAD

**Issue by henrynewman** [SamKirkland/FTP-Deploy-Action#301]
Can you add support for SSH on the current project instead of creating a separate project ([SamKirkland](https://github.com/SamKirkland)/[web-deploy](https://github.com/SamKirkland/web-deploy)) as the current project seems to be updated regularly and widely used by many users.

**Comment by SamKirkland** [comment]
SSH is an entirely different protocol. It makes more sense as it's own package/action
