### ISSUE TITLE
FTP modified only?

### ISSUE THREAD

**Issue by saltnpixels** [SamKirkland/FTP-Deploy-Action#31]
Does this ftp only the changed or modified files or everything each time it runs?

**Comment by srobichaud** [comment]
I was looking into this too and I stumbled upon this issue : https://github.com/SamKirkland/FTP-Deploy-Action/issues/6 

Details on how to implement :
https://github.com/SamKirkland/FTP-Deploy-Action/issues/6#issuecomment-531651535

**Comment by SamKirkland** [comment]
A workaround is in place right now, adding `--ignore-time` to ARGS will only upload differences.
I'm working on v3, it will upload differences using git comparison by default

**Comment by shahzaib91** [comment]
I am stucked it is deploying complete repo instead of changed files is there any solution to it? i tried adding --verbose and i can see all files are being re-deploy

my YML file:

on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: my_hostname
        FTP_USERNAME: my_username
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        ARGS: --verbose

**Comment by SamKirkland** [comment]
[V3 will now only publish different files.](/SamKirkland/FTP-Deploy-Action/releases)

Breaking change: v3 will only publish tracked (committed) files by default. If your file isn't in source control you will have to add it `.git-ftp-include` [see example](/SamKirkland/FTP-Deploy-Action#force-upload-specific-files)
