### ISSUE TITLE
--delete also remove files not in Github

### ISSUE THREAD

**Issue by srobichaud** [SamKirkland/FTP-Deploy-Action#32]
For the purpose of this issue here is my folder structure on Github : 

-/upload
-/upload/file.jpg
-/index.html

On my FTP the structure is : 

-/upload
-/upload/file.jpg
-/upload/my_client_personal_folder/
-/upload/my_client_personal_folder/file.txt
-/index.html

With the `--delete` argument: if I change index.html, the index file is uploaded and /upload/my_client_personal_folder/ and his content is deleted.

But if I don't have `--delete` and I decide to remove /upload/file.jpg, it will not be removed from the FTP.

Is there a way to delete only the files in Github ? So user generated content in the FTP would not be effected, but still retain the ability to remove files.

**Comment by SamKirkland** [comment]
You can add the clients folder to the excluded files list, add this to your ARGS
`--exclude-glob=my_client_personal_folder --exclude-glob=my_client_personal_folder/**`

**Comment by SamKirkland** [comment]
With the [release of v3](/SamKirkland/FTP-Deploy-Action/releases) you can now use a `.git-ftp-ignore` file to ignore specific files or folders. You may not need to do this at all if `/my_client_personal_folder/` isn't tracked (committed) to github. Only tracked files are synced in version 3.
