### ISSUE TITLE
Github has deprecated Node12 actions

### ISSUE THREAD

**Issue by johngeorgewright** [SamKirkland/FTP-Deploy-Action#325]
**Bug Description**
I recently received a notification from Github:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: SamKirkland/FTP-Deploy-Action

Fairly self explanatory, just need to reference a newer version in the [action.yml](https://github.com/SamKirkland/FTP-Deploy-Action/blob/master/action.yml#L48).

**Comment by Olzie-12** [comment]
yep, can you also please do this for 3.1.1 as well :)

**Comment by the-snowwhite** [comment]
There is also:
https://github.com/SamKirkland/FTP-Deploy-Action/pull/329

**Comment by SamKirkland** [comment]
Done!

See v3.1.2 and v4.3.3
