### ISSUE TITLE
getaddrinfo

### ISSUE THREAD

**Issue by tristanvegas** [SamKirkland/FTP-Deploy-Action#331]
Error: Error: getaddrinfo ENOTFOUND ftp.test.com (control socket)

**Comment by dev-charles15531** [comment]
I'm also facing same problem for over 24 hours of trying

**Comment by dev-charles15531** [comment]
@tristanvegas Try using the server IP, did that and it worked for me

**Comment by tristanvegas** [comment]
got new error :D
deploy-action can fill the information 
thanks

**Comment by tristanvegas** [comment]
FTP Username: testusername@test..com
FTP server: ftp.test.com
FTP & explicit FTPS port:  21

**Comment by tristanvegas** [comment]
> @tristanvegas Try using the server IP, did that and it worked for me

got new error :D
deploy-action can fill the information
thanks

**Comment by dev-charles15531** [comment]
On the FTP server, replace ftp.test.com with the server IP address.
