### ISSUE TITLE
Why disable the SFTP protocol?

### ISSUE THREAD

**Issue by Feeh03114** [SamKirkland/FTP-Deploy-Action#333]

**Comment by StevyMarlino** [comment]
I juste have that issue. 
Me too i want to know

**Comment by CleanCodeDeveloper** [comment]
Support for SFTP was removed with the v4 release. 

If you need SFTP you can continue to use the version 3.1.x which still supports SFTP. The maintainer SamKirkland even released an update for the old 3.1 action to make sure it is still usable after github deprecates node12 in favor of node16 (Thanks you very much @SamKirkland ). The maintainer promised in the [release notes of version 4](https://github.com/SamKirkland/FTP-Deploy-Action/releases/tag/4.0.0) to release a new action someday which will support SFTP again. Still holding on to this promise ;-)

**Comment by SamKirkland** [comment]
SFTP is an entirely different protocol andi unfortunately don't have time to support that.

@CleanCodeDeveloper 
web-deploy is the library for those that want secure file transfers, it required SSH.

https://github.com/SamKirkland/web-deploy

**Comment by jemshit** [comment]
@SamKirkland does `web-deploy` support SFTP, as i my credentials don't have SSH terminal access but has SFTP access for file transfer on port 22
