### ISSUE TITLE
Hi, why did I set dangerous-clean-slate to false and still clear the server-dir directory?

### ISSUE THREAD

**Issue by vm0100** [SamKirkland/FTP-Deploy-Action#337]
Hi, why did I set `dangerous-clean-slate` to `false` and still clear the `server-dir` directory?

I want to achieve the purpose of incremental update, do not need to delete the file on the server, what should I do?

![1668689981058](https://user-images.githubusercontent.com/28549702/202452980-e61251ba-7ff2-42c9-aeea-2000692596aa.jpg)
![1668689961038](https://user-images.githubusercontent.com/28549702/202452997-98ac3564-9471-46e5-9d13-12497963aafb.jpg)

**Comment by Trainax** [comment]
Did you delete the file named `2022-11-17-10-49.zip` from the repository? If it is so then the file was deleted by the action because you have deleted it from the repository
