### ISSUE TITLE
No files getting deployed only folders are uploading

### ISSUE THREAD

**Issue by DEV-BDM** [SamKirkland/FTP-Deploy-Action#363]
**Bug Description**
No files getting uploaded at Cpanel FTP but only folders are getting uploaded

on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}

**My Action Log**

Error: None of the available transfer modes work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:[43](https://github.com/DEV-BDM/skillssand/actions/runs/3925396003/jobs/6710288225#step:3:44)23:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Error: None of the available transfer modes work.

**Comment by SamKirkland** [comment]
This should be fixed in `v4.3.4`
