### ISSUE TITLE
Unexpected input(s) 'server-dir', valid inputs are ['entryPoint', 'args', 'ftp-server', 'ftp-username', 'ftp-password', 'local-dir', 'git-ftp-args']

### ISSUE THREAD

**Issue by mufazmi** [SamKirkland/FTP-Deploy-Action#364]
Exception :

Unexpected input(s) 'server-dir', valid inputs are ['entryPoint', 'args', 'ftp-server', 'ftp-username', 'ftp-password', 'local-dir', 'git-ftp-args']

![err](https://user-images.githubusercontent.com/34832943/212823302-b7c5cb2a-b47b-4f62-8755-9205137aed50.png)

**Code that I am using in my workflow:**

      - name: Deploying to Server Via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST_PRODUCTION }}
          ftp-username: ${{ secrets.FTP_USER_PRODUCTION }}
          ftp-password: ${{ secrets.FTP_PASS_PRODUCTION }}
          # local-dir: ./build/
          server-dir: home/server_home/stage.abc.com/

**Comment by SamKirkland** [comment]
You are using a very old version of the library (version `3.1.1`) but you are reading the newest documentation.

[Here is the documentation for version 3.1.1](https://github.com/SamKirkland/FTP-Deploy-Action/tree/v3.1.1) - for future reference simply click on the branches dropdown, then select the version
