### ISSUE TITLE
create tags in `v4.x.x` format instead of `4.x.x` format.

### ISSUE THREAD

**Issue by amithm7** [SamKirkland/FTP-Deploy-Action#374]
Tags of the format `4.x.x` create few problems:

- [Tags](https://github.com/SamKirkland/FTP-Deploy-Action/tags) and [releases](https://github.com/SamKirkland/FTP-Deploy-Action/releases) are ordered incorrectly (`4.x.x` should have been at the top).
- [GitHub Marketplace listing](https://github.com/marketplace/actions/ftp-deploy) marks incorrect version as latest: gh-381
- gh-294

Please create `v4.x.x` format tags.

Here, is a script for convenience, creating `v*` tags on old `X.X.X` tags:

```sh
#!/bin/bash

# Get all existing tags
tags=$(git tag)

# Iterate over each tag
for tag in $tags; do
  # Check if the tag matches the X.X.X format
  if [[ $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    # Create the equivalent vX.X.X tag
    git tag "v$tag" "$tag^{}"
  fi
done

# Push the new tags to the remote repository
git push --tags
```

You may leave the old tags of the format `4.x.x` as it is.

**Comment by michael-letcher** [comment]
Please update, super annoying to see the versions causing old outdated versions appearing in the Git marketplace

**Comment by SamKirkland** [comment]
Oh wow I had no idea the marketplace listed these out of order. Thanks for the heads up.

Looks like the marketplace uses the order of releases and does NOT look at the release tagged latest!
![image](https://user-images.githubusercontent.com/7682814/225211285-0b2d4338-36f9-4c3f-ac97-2fe81ed38059.png)

When clicking "Use latest version" 
![image](https://user-images.githubusercontent.com/7682814/225211367-667ff546-8b45-4650-8014-b537e81de8f1.png)

Your script worked and I've added an additional `vx.x.x` tag to all releases & old tags. However it did not fix the issue. Looks like github is actually using the tagged date 😢 

https://github.com/github-changelog-generator/github-changelog-generator/issues/244#issuecomment-665026391

Will look into a fix here, I should be able to mutate the tagged date.

**Comment by SamKirkland** [comment]
Closing this out.

Wasn't able to resolve the issue with releases being out of order. I need to associate a tag with a commit... and I DID push a hotfix to those tags, so it's technically correct.

I removed the old versions from the marketplace, going forward I will use `vx.x.x` tags and only keep the newest version or two on the marketplace

**Comment by amithm7** [comment]
Were you using annotated tag?
