### ISSUE TITLE
Only folders are deploying not files

### ISSUE THREAD

**Issue by asifulmamun** [SamKirkland/FTP-Deploy-Action#378]
**Bug Description**

Showing all files and folder creating and uploading while deploying. Actually not upload all of the files, only make all of the folders only not files.

**Comment by samuelbosawer** [comment]
Change version

**Comment by asifulmamun** [comment]
> The same problem here. Only folders deployed. @asifulmamun did You manage to resolve this? Downgrading to 2.0.0 doesn't seem like a good idea. @SamKirkland any chance getting a fix?

Thanks, but I haven't tried it yet
