### ISSUE TITLE
LFS Objects are not being copied

### ISSUE THREAD

**Issue by Dreamfish19** [SamKirkland/FTP-Deploy-Action#38]
Hi,

thanks for this great Action!

I have a repository with GIT LFS Objects (https://git-lfs.github.com/). 

But the LFS files (for example MP4-Videos) are not transfered via FTP, but the references,
which are basically textfiles.

Is it possible that this action will also transfer the bigger files?

**Comment by SamKirkland** [comment]
Hey, glad you're finding this action useful!

You need to update your checkout action to download the large files, to do that set the `lfs` option to true.

Example:
```
- uses: actions/checkout@v2
  with:
    lfs: true
```

Leave a comment if that doesn't resolve the issue and we can take a deeper look.
