### ISSUE TITLE
Request: Upload to temporary first, then overwrite the old version

### ISSUE THREAD

**Issue by lassespilling** [SamKirkland/FTP-Deploy-Action#396]
Hi, would it possible to upload to a temporary folder first, then "rename / replace" the old folder?

e.g updating this folder on a server:
/build

1. **Upload** /build-4534938
3. **Rename** /build to /build-old
4. **Rename** /build-4534938 to /build
5. **Delete** /build-old

If the production folder is large, then the replace action will make the website have downtime.
It would be better to do a quick

**Comment by SamKirkland** [comment]
[V4+ already minimizes downtime](https://github.com/SamKirkland/FTP-Deploy-Action/pull/117)

> The deployment is now setup in a way that minimizes downtime. For example, new files can be uploaded, then existing files updated, and finally old files deleted.

This approach was taken over a upload & rename approach. The upload and rename approach would require all files be re-uploaded on every deploy which takes too long.

**Comment by lassespilling** [comment]
Awesome.
