### ISSUE TITLE
Build script only fires when created

### ISSUE THREAD

**Issue by senner007** [SamKirkland/FTP-Deploy-Action#4]
I commit  .github/workflows/main.workflow
```
workflow "ftp deploy" {
  resolves = ["FTP-Deploy-Action"]
  on = "push"
}

action "FTP-Deploy-Action" {
  uses = "SamKirkland/FTP-Deploy-Action@master"
  secrets = ["GITHUB_TOKEN", "FTP_SERVER", "FTP_PASSWORD", "FTP_USERNAME", "LOCAL_DIR", "REMOTE_DIR"]
}
```
But it only starts when I commit the script. Not on each push?

**Comment by senner007** [comment]
It only runs when I add the main.workflow script. It does not run on each push to the repo

**Comment by senner007** [comment]
Thanks, but that doesn't work either. Then it is as if I have no actions at all and I get presented with starter templates when I press the actions tab in github

**Comment by senner007** [comment]
If I move back into .github/workflows and commit it starts to run. But not on each push

**Comment by senner007** [comment]
This is no longer relevant, since I can just put it in a yaml file instead:
https://github.com/SamKirkland/FTP-Deploy-Action/issues/3

**Comment by SamKirkland** [comment]
Awesome I'm glad you got everything working!
I'm going to update the documentation to reflect the yaml changes.

**Comment by SamKirkland** [comment]
Documentation is updated!
