### ISSUE TITLE
"Atomic" deploy?

### ISSUE THREAD

**Issue by duzenko** [SamKirkland/FTP-Deploy-Action#407]
**Bug Description**
I use [FTP-Deploy-Action](https://github.com/SamKirkland/FTP-Deploy-Action) to deploy a React app.
It means that I have to use `dangerous-clean-slate: true` in order to remove previous version files.
Since the upload takes a while, all that time the production system is in a half-broken state due to partially missing files.

Is it possible to upload to a temporary directory instead and just rename it in the end?
Or achieve the same goal in some other way (e.g. first upload new files, then overwrite what changed, and in the end delete files not found on `this` side)?

**My Action Config**
```TBD```

**My Action Log**
```
ALL OK
```

**Comment by duzenko** [comment]
Related: https://github.com/SamKirkland/FTP-Deploy-Action/issues/396

**Comment by SamKirkland** [comment]
> It means that I have to use `dangerous-clean-slate: true` in order to remove previous version files.

This isn't true. I strongly recommend you use [the example in the readme instead](https://github.com/SamKirkland/FTP-Deploy-Action#build-and-publish-reactangularvue-website) - `dangerous-clean-slate` is not needed to delete old files on v4+.



> Is it possible to upload to a temporary directory instead and just rename it in the end?
> Or achieve the same goal in some other way (e.g. first upload new files, then overwrite what changed, and in the end delete files not found on `this` side)?

This action already minimizes downtime by:

1. Creating new files
2. Modifying existing files
3. Deleting removed files

[See code](https://github.com/SamKirkland/ftp-deploy/blob/198e42578e83114191d3ed2377cce76c66d3abec/src/deploy.ts#L157)
