### ISSUE TITLE
530 Login authentication failed

### ISSUE THREAD

**Issue by Sarwar242** [SamKirkland/FTP-Deploy-Action#413]
Log:
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 530 Login authentication failed
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5252:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5096:44)
    at Socket.emit (node:events:513:[28](https://github.com/mateaustralia/repairmate/actions/runs/5878283930/job/15940034746#step:3:29))
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 5[30](https://github.com/mateaustralia/repairmate/actions/runs/5878283930/job/15940034746#step:3:31)
}
Error: FTPError: 5[30](https://github.com/mateaustralia/repairmate/actions/runs/5878283930/job/15940034746#step:3:31) Login authentication failed

I am using the same credentials which work on Filezilla. This is very frustrating...

**Comment by nooneofyourbuisness** [comment]
facing same issue please tell the slution

**Comment by quiet-programmer** [comment]
> ## Log:
> ## 🚀 Thanks for using ftp-deploy. Let's deploy some stuff!
> 
> If you found this project helpful, please support it by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.
> ## -------------- 🔥🔥🔥 an error occurred 🔥🔥🔥 --------------
> ## ---------------------- full error below ----------------------
> 
> FTPError: 530 Login authentication failed at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5252:39) at Socket. (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5096:44) at Socket.emit (node:events:513:[28](https://github.com/mateaustralia/repairmate/actions/runs/5878283930/job/15940034746#step:3:29)) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:285:11) at Socket.Readable.push (node:internal/streams/readable:228:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23) { code: 5[30](https://github.com/mateaustralia/repairmate/actions/runs/5878283930/job/15940034746#step:3:31) } Error: FTPError: 5[30](https://github.com/mateaustralia/repairmate/actions/runs/5878283930/job/15940034746#step:3:31) Login authentication failed
> 
> I am using the same credentials which work on Filezilla. This is very frustrating...

Hey @Sarwar242 I'm guessing you are using a Cpanel... I have been using this frp actions for going 1 year now and I havenot had any issues with you.

I will advise not to use your FTP login, but your actual Cpanel Login details, this is what always works for me

**Comment by Timoumi-Mahmoud** [comment]
Hello do you have solved the problem , I have the same here .

**Comment by Sarwar242** [comment]
No. In my case, it didn't work in any ways. So, I used another package.

**Comment by krishnaglodha** [comment]
> No. In my case, it didn't work in any ways. So, I used another package.

What package have you tried ?
