### ISSUE TITLE
Support for "--ignore-time"

### ISSUE THREAD

**Issue by skrysmanski** [SamKirkland/FTP-Deploy-Action#429]
I'm creating a static web site with Hugo (which creates static html files from markdown files). As a result, every time my workflow runs, all generated .html files have "now" as date/time.

So, when I'm using the FTP-Deploy-Action, it always detects all html files as new and re-uploads them.

Over at <https://github.com/SamKirkland/ftp-deploy> I found some mention of the `--ignore-time` option but it doesn't seem to be supported in the GitHub action.

Could you add support for it? (Or am I missing something here?)

Also, when using `--ignore-time` does your action still do a hash comparison? (I've noticed that the state json contains a hash for each file.)

**Comment by skrysmanski** [comment]
Thanks for the quick reply. I'm actually using the newest version but with your answer I figured out that some file (hashes) actually change. So, everything is good :)

**Comment by SamKirkland** [comment]
Oh nice!
Where did you see --ignore-time in the docs? Just curious so i can clean that up.
