### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by ramzlab000** [SamKirkland/FTP-Deploy-Action#434]
The action displays the following warning:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, SamKirkland/FTP-Deploy-Action@v4.3.4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by rasulsh** [comment]
I’m dealing with the same problem as you

**Comment by ramzlab000** [comment]
I think there's already a pull request https://github.com/SamKirkland/FTP-Deploy-Action/pull/415 - this should fix the issue!

**Comment by rasulsh** [comment]
> I think there's already a pull request #415 - this should fix the issue!

As of now, since it hasn't been merged with the master branch and the new version hasn't been released, we'll have to wait

**Comment by maverage** [comment]
I updated the dependencies and built it with node 20 without issues, seems to be working for me https://github.com/maverage/FTP-Deploy-Action/releases/tag/v4.3.5

I hope it will be fixed here soon, I created a PR #435

**Comment by ramzlab000** [comment]
> I updated the dependencies and built it with node 20 without issues, seems to be working for me https://github.com/maverage/FTP-Deploy-Action/releases/tag/v4.3.5
> 
> I hope it will be fixed here soon, I created a PR #435

I'm using yours for now. Thanks!

**Comment by SamKirkland** [comment]
Available in the latest v4.3.5 release
