### ISSUE TITLE
v4.3.4 not found

### ISSUE THREAD

**Issue by ilonashairstyling** [SamKirkland/FTP-Deploy-Action#438]
Upgraded to v4.3.4, but system was not able to find:

 Current runner version: '2.312.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `SamKirkland/FTP-Deploy-Action@4.3.4`, unable to find version `4.3.4`

**Comment by maverage** [comment]
It confused me as well, but the Tag of version 4.3.4 is SamKirkland/FTP-Deploy-Action@v4.3.4, not SamKirkland/FTP-Deploy-Action@4.3.4.

**Comment by ilonashairstyling** [comment]
I confirm it is working now. Thank you for your quick reply.
