### ISSUE TITLE
Deploy fails with "fatal: Remote host not set."

### ISSUE THREAD

**Issue by vvye** [SamKirkland/FTP-Deploy-Action#44]
Thanks for continuing to update this! Unfortunately, I can't seem to get version 3 to work.

Here's the relevant part of my .yml, which I had updated according to the migration guide:

```on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          ftp-server: ftp://example.com/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
```

And here's how that fails to work:
![grafik](https://user-images.githubusercontent.com/13839342/75033766-e8cb4d80-54ab-11ea-803d-bf7b49330de6.png)

I've tried specifying the hostname with and without a trailing slash, and I've tried both ftp and sftp. There's obviously something I'm blatantly missing, I'm just not sure what.

Help would be appreciated!

**Comment by SamKirkland** [comment]
Sorry for the delay. I haven't had a chance to look into this yet, however I believe I know the cause.

Exit code 3 is MissingArguments and your password should automatically be masked with *** (github actually does this automatically if you store the password as a secret).

Would you password by chance include any special characters? Specifically a space ` ` or space or a space and comment character ` #`? When the `#` character is used anything after it is considered a comment, in this case your host.

To resolve this you should be able to escape your password.

**Comment by vvye** [comment]
Thanks for the reply! The password contained a double quote ("), and assuming that's counted as an escape character, that might very well be the reason.

Though would that also explain why the password wasn't masked? I definitely did store it as a secret.

I've since changed the password and also switched back to 2.0.0. The new password looks like it'd play nicer with version 3; I'll let you know how it goes in a bit.

**Comment by vvye** [comment]
Yep, using a new password without escape characters resolves the issue with version 3 - and that also makes the password properly hidden in the log file.

Pretty obvious in hindsight, but I don't think I'd have figured it out without your input, so thanks very much.
