### ISSUE TITLE
Upload  error

### ISSUE THREAD

**Issue by vol4ikman** [SamKirkland/FTP-Deploy-Action#443]
**Bug Description**
----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------
Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5299:33)
    at Object.onceWrapper (node:events:628:28)
    at Socket.emit (node:events:514:28)
    at Socket._onTimeout (node:net:589:8)
    at listOnTimeout (node:internal/timers:573:[17](https://github.com/vol4ikman/wp-guru/actions/runs/8124003462/job/22205017332#step:3:18))
    at process.processTimers (node:internal/timers:514:7)
Error: Error: Timeout (control socket)

**My Action Config**
```on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
```

**Comment by davoodimhmd** [comment]
I got same error!
please help

**Comment by SamKirkland** [comment]
This is a duplicate issue, #106 
Did you recently upgrade to v4.3.5 from an older version? If so what version were you on previously? Did the old version have this error?

**Comment by vol4ikman** [comment]
> This is a duplicate issue, #106 Did you recently upgrade to v4.3.5 from an older version? If so what version were you on previously? Did the old version have this error?

No. There is a clear installation. No upgrade was madden.

**Comment by davoodimhmd** [comment]
> > This is a duplicate issue, #106 Did you recently upgrade to v4.3.5 from an older version? If so what version were you on previously? Did the old version have this error?
> 
> No. There is a clear installation. No upgrade was madden.

If you are using cloudflare or other service like this you should disable cloud service then it will be ok. It works for me
