### ISSUE TITLE
Local dir set, but parent folders are still being uploaded

### ISSUE THREAD

**Issue by Wouter8** [SamKirkland/FTP-Deploy-Action#46]
My understanding is that `local-dir` is `syncroot` from git-ftp. `syncroot` should set the repository root to that folder. I have an Angular project which builds to `./wv8-finance-front-end/dist/`. 

Therefore, I've added the folder to the include file:
`!wv8-finance-front-end/dist/`

And set the local-dir to:
`./wv8-finance-front-end/dist/`.

When uploading I'd expect the files in the dist folder to be uploaded to the root of my specified path. Sadly both folders (wv8-finance-front-end/dist) are being uploaded with the files in the dist folder. I need the files to be in the root folder.

Am I doing something wrong? Thanks in advance.

**Comment by ME-QEOS** [comment]
I'm having a similar issue.

My .git-ftp-include contains

> !www/
> !platforms/android/app/build/outputs/apk/debug/

In my release workflow, I deploy to FTP-server A with `local-dir: www/` which works perfectly.
But when I deploy to FTP-server B with `local-dir: platforms/android/app/build/outputs/apk/debug/` (in the same workflow) it also uploads the www-folder.

So I would assume that it would only upload the contents of the debug-folder.

**Comment by SamKirkland** [comment]
Sorry for the delay @Wouter8 and @ME-QEOS
I was able to look into this today. 

@Wouter8 for your issue I believe you need to remove the `./` in front of your `local-dir`. 

Please do the following:
1) Delete synced files on your server for a fresh start
2) Change the `local-dir` config change (new `local-dir` setting should be `wv8-finance-front-end/dist/`)
3) Try the sync again and report back with the results


----

@ME-QEOS your issues is more complicated. Using `!` tells git-ftp to [always upload files](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#syncing-untracked-files), Could you associate the www folder with a git tracked file?

#### Example
```yaml
www/:changelog.txt # if changelog.txt has changed www is uploaded
```

**Comment by ME-QEOS** [comment]
Hi @SamKirkland 

Adding www to git would be a hassle, because it is the output directory of a build process.
The generated files are always unique per build, so I can't hardcode them.

As a solution to myself, I've used (and modified) an action from one of your "competitors" :-)
--> https://github.com/sebastianpopp/ftp-action
This action allows me to specify an exact directory without adding it to git and whatnot.

**Comment by SamKirkland** [comment]
version 4 resolves this
