### ISSUE TITLE
Translate error code

### ISSUE THREAD

**Issue by Triloworld** [SamKirkland/FTP-Deploy-Action#48]
After installation and setup I get:

> The process 'git' failed with exit code 8

Next try:

> The process 'git' failed with exit code 5

All cryptic and irrelevant

This isn't in standard "git" error code. It come from library: 
https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#exit-codes

Even that, code wasn't proper one.
My host have firewall (block IP) and this stop first random action (so download or upload)

Propose rewrite number code in failed message to actually message from library (as a Hint in second line). Maybe link to place where exit codes is? Add info to check details where is really more info?

As this repo is about action, message can help diagnose where look for error and don't create another issues there but in proper place.

Screen looks like that, yes - I can check details, but first think what looks is that error isn't from my side:
<img width="1324" alt="Zrzut ekranu 2020-03-15 o 14 26 06" src="https://user-images.githubusercontent.com/2671726/76702311-2b5a0180-66c9-11ea-842c-da2dd880ce79.png">

**Comment by kapoko** [comment]
I got this error when I forgot to use `- uses: actions/checkout@v2` on the ftp deploy job. 

I was trying to separate the build and deploy into 2 jobs as experiment, but that wasn't right, as workspaces aren't copied over to another job.

**Comment by SamKirkland** [comment]
Great idea @Triloworld - I'll make this change on the next update.
I actually have the [error codes mapped in models](https://github.com/SamKirkland/FTP-Deploy-Action/blob/98039f1fbe3b78495d8fb6acce43c1e8c259a7ae/src/types.ts#L16), I just don't use them for anything 🤦‍♂

**Comment by Triloworld** [comment]
Can be more descriptive?
Maybe like this example (5): 

> ErrorWhileUploading
> Check details in log and in [FAQ](https://github.com/SamKirkland/FTP-Deploy-Action#faq)

FAQ - in another issue this section need little refactor to this proposition.
We can describe more details about what check before creating issue, what error might be releated to this repo, where look for more information.

**Comment by SamKirkland** [comment]
version 4 has better error messages.
