### ISSUE TITLE
Refactor proposal: FAQ

### ISSUE THREAD

**Issue by Triloworld** [SamKirkland/FTP-Deploy-Action#53]
We need FAQ (https://github.com/SamKirkland/FTP-Deploy-Action#faq) to be refactor and detailed.

Propose:
1. First point need to adress information that connection is between GitHub Action <-> Remote server
```
Check:
- open details in arrow where more information is available
- is IP from USA/EU enable to access HOST?
- is credentials proper?
- use "git-ftp-args: --insecure" as there can be misconfiguration on remote server with secure connection
- check firewall, iptables, hostname resolution, cache (24h wait)
```
2. Point second need additional info:
```
Any file outside of repository, generated in other step won't be uploaded.
Use check .git-ftp-include what is included in push and .git-ftp-ignore what are ommit.
```
3.  Third point
There need more information about permission. This file is alphabetically first on list and because that is error on one file. Many files on host must be disabled from sync.

4. Four point need add example

5. Any point need to be linkable as header (https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#section-links) and format correctly  - more precise answer in issue reply.

6. Maybe add --test flag for uploading example file (permission, connection and stuff before git command run). Required to run before new issue created.

7. Maybe use detail syntax in points https://github.github.com/gfm/#html-blocks ?
<details>
Description for point
</details>

8. Link to other resource as GIT, GIT PUSH, FTP protocol, maybe somewhere is instruction about all connection case issue?

I will help with content but asking what direction is going this github action. No roadmap, no wiki, no guildlines and there exist double issue on same topic. Maybe add to Readme about what type of contribution and what thinks that GitHub Action must do and don't ? No need to bloat simple think, just have production grade solution on some weird ftp host.

**Comment by SamKirkland** [comment]
1. Updated this section, please take a look
2. I've added links to the examples
3. What other files? I can add to the list if you give me some examples
4. I added a link to the example
5. You want FAQ items to be headers so we can link to them? I've added id's to detail sections
6. This would be a technically difficult thing to do. It's hard to automatically diagnosis the issue
7. Changed all FAQ points to `details`
8. Linked to in the settings section

**Comment by SamKirkland** [comment]
Closing this issue for now, let me know if you want to discuss your ideas on the wiki more.
