### ISSUE TITLE
Is it possible to deploy only the changed files since the last deployment?

### ISSUE THREAD

**Issue by hussainb** [SamKirkland/FTP-Deploy-Action#6]
Thanks for the wonderful script.
Is it possible to deploy only the changed files since the last deployment instead of copying the whole repo everytime?

**Comment by JordyValentine** [comment]
Hi @hussainb 
I'm not involved with the project, but I noticed that uploading only the differences is one of the item's listed in the 'ToDo' section of the readme.

> ### ToDo
> - More config options
>    - Deploy Mode: ${DEPLOY_MODE} `full`|`diffs`

Hopefully it can be added soon

**Comment by SamKirkland** [comment]
@JordyValentine thanks for the response

@hussainb and @JordyValentine I'm going to take a look at implementing this feature. Hopefully I can have something working this week, i'll update this ticket when I've got something working.

**Comment by hussainb** [comment]
There is a similar action named git-ftp-action which uses git-ftp but it didnt work for me (after updating it) because git-ftp has to be initialized first with `git ftp init` or `git ftp catchup`.
but since a new instance of container is always created by github, I am not clear on how the previous state can be retained when always a new instance is run. you might have some workaround for it, maybe.

**Comment by SamKirkland** [comment]
@hussainb and @JordyValentine I've added this feature!
By default this action will now only deploy files that are different than the server.

To opt into a full deploy use the `--transfer-all` option (see readme)

**Comment by JordyValentine** [comment]
Thanks so much @SamKirkland 👍️ I'll give it a test tonight

**Comment by harrisonratcliffe** [comment]
For some reason all the files are being transferred regardless, is this feature still implemented?

**Comment by developerwill** [comment]
It doesn't work. It always uploads everything.
