### ISSUE TITLE
Formal release for known-hosts?

### ISSUE THREAD

**Issue by sambrenner** [SamKirkland/FTP-Deploy-Action#65]
**Bug Description**
I was trying to figure out why my `known-hosts` wasn't working when I realized that the code to handle (#55) it is not part of the 3.0.0 release. All of the example code in the readme has 

    uses: SamKirkland/FTP-Deploy-Action@3.0.0

but to take advantage of `known-hosts`, I had to switch it to

    uses: SamKirkland/FTP-Deploy-Action@master

Could you do a formal release of the `known-hosts` functionality so I don't have to hook on to the `master` branch going forward? Or maybe note it in the readme so it's clear for anyone else who wants to use it - this took me longer than I'd like to admit to debug! (I'd be happy to open a PR for readme edits as well if you'd like)

Thanks for all your hard work!

**Comment by SamKirkland** [comment]
Thanks for letting me know.
I've created [a release for known-hosts](https://github.com/SamKirkland/FTP-Deploy-Action/releases) `v3.1.0`
