### ISSUE TITLE
Default exclusion of the .github-folder

### ISSUE THREAD

**Issue by simmac** [SamKirkland/FTP-Deploy-Action#66]
Currently, unless explicitly excluded via the .git-ftp-ignore file, the .github-folder used for Actions is transferred. In my opinion, this may be a security risk as Actions-workflow configuration files may leak sensitive information, such as endpoints used for the build chain, in the case of this Action FTP hostname and username etc. I would guess 95%+ of the developers using this action do not want to transfer the `.github`-folder to their FTP-server.

I would suggest to add `.github` to the ignore-file per default and add a flag to explicitly include the folder if the user wishes to do so.

If this is not desired, I would at least recommend adding a clear warning/notice about this behavior (this behavior is logical and follows from the way `git-ftp` works, but it's easy to miss (happened to me)).

**Comment by SamKirkland** [comment]
version 4 excludes all .git** files/folders by default
