### ISSUE TITLE
open: ***: Name does not resolve

### ISSUE THREAD

**Issue by AhoyLemon** [SamKirkland/FTP-Deploy-Action#7]
Hi, 

Apologies if there's a better place to put this issue. I've just tried to implement this into a project and every build is failing. I have my three secrets set up (`FTP_SERVER`, `FTP_USERNAME` and `FTP_PASSWORD`) but when I look into the Actions tab it fails.

![image](https://user-images.githubusercontent.com/3413200/64540772-4dbc2e00-d2e6-11e9-98d5-2ff0a3c3691b.png)

**FTP Deploy Action:**
```
Run SamKirkland/FTP-Deploy-Action@master

          

            env:

          

              FTP_PASSWORD: ***

          

              FTP_SERVER: ***

          

              FTP_USERNAME: ***

          
/usr/bin/docker run --name df7dc5a975570098d4c0ebb70c109605185a5_c21419 --label 0df7dc --workdir /github/workspace --rm -e FTP_PASSWORD -e FTP_SERVER -e FTP_USERNAME -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/██████/██████":"/github/workspace" 0df7dc:5a975570098d4c0ebb70c109605185a5
Starting FTP Deploy
Uploading files...
open: ***: Name does not resolve
```

Googling isn't helping me figure out what this "name does not resolve" thing means, hoping you could help?

**Comment by SamKirkland** [comment]
Hey sorry for the delay,

You see "***" in your message because github automatically censors any secrets.
My best guess is your FTP server cannot be found. does your FTP_SERVER secret look something like "ftp.samkirkland.com" (no protocol, etc)
You should be able to access this in your browser via ftp://{FTP_SERVER} (example: ftp://ftp.samkirkland.com/)

**Comment by SamKirkland** [comment]
@AhoyLemon Any luck getting it to work?
If you're still having the issue I can help your troubleshoot. Please replace the FTP_SERVER secret with an inline string so github doesn't *** out the server so we can verify that's the issue.

example:
```shell
env:
  FTP_SERVER: ftp.samkirkland.com
  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
```

**Comment by SamKirkland** [comment]
@AhoyLemon Any update or can I close this ticket?

**Comment by AhoyLemon** [comment]
Well, that's embarassing.

You were totally 100% correct and it was entirely my fault. I fat fingered the `FTP_SERVER` secret, and didn't think to retry *that* before submitting the issue.

Just tried again and the action successfully completed. Thank you.

**Comment by SamKirkland** [comment]
Awesome i'm glad it worked out!
