### ISSUE TITLE
Failed to connect to "mydomain.com". Connection timed out

### ISSUE THREAD

**Issue by kiikoh** [SamKirkland/FTP-Deploy-Action#75]
I can easily connect with a ftp client like winscp.

Don't know what is happening wrong.

Password has symbols including @s and $. Is this a possible issue?

**Comment by Rowin206** [comment]
Please share your action log & workflow file. Oh and you can already try a different password, right?

**Comment by SamKirkland** [comment]
Special characters should work fine. I did some digging into this and noticed spaces won't work properly on `v3.1.0`. I've fixed that with release `v3.1.1`.

If you switch your version over to 3.1.1 you can try again.
```yaml
uses: SamKirkland/FTP-Deploy-Action@3.1.1
```
