### ISSUE TITLE
Clear remote folder before or after deploy

### ISSUE THREAD

**Issue by Misiu** [SamKirkland/FTP-Deploy-Action#8]
Hi there,
I recently starder using Your action. After couple of tries, I got it working.
I use react and when creating build js files are minified and hash is added to names (to prevent cache problems). When deploying multiple times I end up with one working js file and couple of outdated files (because they stay on the server).
Ideally, I'd like to remove old files after deploy, but this would involve listing files on FTP, then listing files in build directory and deleting only those that didn't change on deploy, but easier solution would be to add option that will allow deleting all files (and folders) in remote directory before deploy (upload) starts.
Please consider adding this feature.

**Comment by SamKirkland** [comment]
I'm looking into adding this as an option, I'll update this ticket when I've got it working,

On another note what issues did you have getting the action working? I'd love to add a Common issues section to the readme or improve documentation so any feedback you have is welcome.

**Comment by Misiu** [comment]
@SamKirkland I had problem with correctly declaring local and remote dirs. I didn't know should I include trailing slashes or backslashes.
If I remember correctly as first I added slash at the end of remote_dir and all files from my local_dir were uploaded to toot of my FTP.

This could be added to Common Issues or even fixed by Your script (tailing slashes should be added or removed if needed)

Now when I think about my feature request (deleting files on ftp) I'd like to ask for one more. There should be one additional parameter `test_mode` (default to false) that would print dirs and files instead of doing actual actions.
Users need to be 100% sure that script will remove files in correct dir. I can't imagine deleting my whole FTP (unfortunatelly I have single user/pass 😟)

**Comment by SamKirkland** [comment]
@Misiu
I've added both your suggestions!
Check out `--delete` and `--dry-run` in the readme.

I've also updated the readme to make the local/remote dir options more clear.

I'm going to close this issue out, thanks for the great suggestions.

**Comment by Misiu** [comment]
Perfect! Thank You 🙂
I'll try that right away.

BTW: Why do You use action name with lower f (`fTP-Deploy-Action`) in the readme? Shouldn't it be `FTP-Deploy-Action`

**Comment by ozgurg** [comment]
> @Misiu
> I've added both your suggestions!
> Check out `--delete` and `--dry-run` in the readme.
> 
> I've also updated the readme to make the local/remote dir options more clear.
> 
> I'm going to close this issue out, thanks for the great suggestions.

I didn't see "--delete" argument in the README. Is it still available?

**Comment by Misiu** [comment]
@ozgurg it was there before (https://github.com/SamKirkland/FTP-Deploy-Action/commit/9c4e4646b8b71d9ff86cfb1a44395ce36bf5ae56#diff-04c6e90faac2675aa89e2176d2eec7d8, search for `delete`), but probably something changed in v3.
