### ISSUE TITLE
The process '/usr/bin/git' failed with exit code 8

### ISSUE THREAD

**Issue by ErikFisherGitHub** [SamKirkland/FTP-Deploy-Action#86]
**Bug Description**
Hello!

I'm Erik, a novice web developer. I want to get GitHub to upload my changed files to the FTP server after every push. I created this error message because, after the push, I get this error message under the action tab. 

> .github#L1
> The process '/usr/bin/git' failed with exit code 8
> 

I would really like FTP-Deploy-Action if it worked.

**My Action Config**
```yaml

> on:
>   push:
>     on: push
> name: FTP feltöltés
> jobs:
>   FTP-Deploy-Action:
>     name: FTP-Deploy-Action
>     runs-on: ubuntu-latest
>     steps:
>     - uses: actions/checkout@v2.1.0
>       with:
>         fetch-depth: 2
>     - name: FTP-Deploy-Action
>       uses: SamKirkland/FTP-Deploy-Action@3.1.1
>       with:
>         ftp-server: ${{ secrets.FTP_SERVER }}
>         ftp-username: ${{ secrets.FTP_USERNAME }}
>         ftp-password: ${{ secrets.FTP_PASSWORD }}
>         local-dir: ${{ secrets.FTP_DIR }} 

```

**My Action Log**
```
> .github#L1 The process '/usr/bin/git' failed with exit code 8
```

**Comment by ErikFisherGitHub** [comment]
I have used an old path for the server.

**Comment by izshreyansh** [comment]
@ErikFisherGitHub old path as in old `local-dir` ?
