### ISSUE TITLE
Issue with WordPress 

### ISSUE THREAD

**Issue by banna360** [SamKirkland/FTP-Deploy-Action#99]
**Bug Description**
I am using this action with wordpress, I am ignoring  core wordpress file in my repo and using your action to deploy to my server. And all files are success fully transferring to my server. Then i am adding  WP Core file manually in server and everything is working fine. 
Later i made some changes to my theme file in repo and run this action. once the action finish i can see only these repo tracked file in server my old file/folder exist in server getting deleted.

Is there any setting it only replace file or add file in site no delete any existing file/folder in server ?

**Comment by SamKirkland** [comment]
version 4 performs a sync by default. meaning any changes will be propagated to the server.
